// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddressStandardizer.proto

package com.equifax.fabric.dataprep.geocoder;

public final class AddressStandardizer {
  private AddressStandardizer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransTasmanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransTasmanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransTasmanResponse_TransTasmanResponseOutputFields_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransTasmanResponse_TransTasmanResponseOutputFields_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AUResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AUResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AUResponse_AUResponseOutputFields_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AUResponse_AUResponseOutputFields_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NZResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NZResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NZResponseOutputFields_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NZResponseOutputFields_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NZResponseError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NZResponseError_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031AddressStandardizer.proto\"1\n\007Request\022\017" +
      "\n\007address\030\001 \001(\t\022\025\n\rcorrelationId\030\002 \001(\t\"\306" +
      "\014\n\023TransTasmanResponse\022J\n\014OutputFields\030\001" +
      " \001(\01324.TransTasmanResponse.TransTasmanRe" +
      "sponseOutputFields\022\025\n\rcorrelationId\030\002 \001(" +
      "\t\032\313\013\n\037TransTasmanResponseOutputFields\022\017\n" +
      "\007nzMALID\030\001 \001(\t\022\014\n\004city\030\002 \001(\t\022\020\n\010postcode" +
      "\030\003 \001(\t\022\016\n\006suburb\030\004 \001(\t\022\022\n\nstreetName\030\005 \001" +
      "(\t\022\022\n\nstreetType\030\006 \001(\t\022\024\n\014streetSuffix\030\007" +
      " \001(\t\022\022\n\npostalType\030\010 \001(\t\022\021\n\taddressId\030\t " +
      "\001(\t\022\020\n\010houseNo1\030\n \001(\t\022\024\n\014houseSuffix1\030\013 " +
      "\001(\t\022\020\n\010houseNo2\030\014 \001(\t\022\024\n\014houseSuffix2\030\r " +
      "\001(\t\022\020\n\010flatType\030\016 \001(\t\022\016\n\006flatNo\030\017 \001(\t\022\021\n" +
      "\tlevelType\030\020 \001(\t\022\017\n\007levelNo\030\021 \001(\t\022\025\n\rbui" +
      "ldingName1\030\022 \001(\t\022\025\n\rbuildingName2\030\023 \001(\t\022" +
      "\r\n\005lotNo\030\024 \001(\t\022\020\n\010postalNo\030\025 \001(\t\022\024\n\014post" +
      "alPrefix\030\026 \001(\t\022\024\n\014postalSuffix\030\027 \001(\t\022\014\n\004" +
      "flag\030\030 \001(\t\022\022\n\nflagString\030\031 \001(\t\022\023\n\013preAdd" +
      "ress1\030\032 \001(\t\022\023\n\013preAddress2\030\033 \001(\t\022\020\n\010addr" +
      "ess1\030\034 \001(\t\022\020\n\010address2\030\035 \001(\t\022\020\n\010address3" +
      "\030\036 \001(\t\022\023\n\013postAddress\030\037 \001(\t\022\023\n\013amendedFl" +
      "ag\030  \001(\t\022\020\n\010rdNumber\030! \001(\t\022\021\n\tvalidFlag\030" +
      "\" \001(\t\022\032\n\022validFlagCorrected\030# \001(\t\022\020\n\010gif" +
      "Flags\030$ \001(\t\022\020\n\010latitude\030% \001(\t\022\021\n\tlongitu" +
      "de\030& \001(\t\022\023\n\013reliability\030\' \001(\t\022\014\n\004dpid\030( " +
      "\001(\t\022\027\n\017mailDeliverable\030) \001(\t\022\023\n\013oldPostc" +
      "ode\030* \001(\t\022\r\n\005sadid\030+ \001(\t\022\014\n\004mb06\030, \001(\t\022\014" +
      "\n\004mb13\030- \001(\t\022\020\n\010areaUnit\030. \001(\t\022\020\n\010wardDe" +
      "sc\030/ \001(\t\022\016\n\006tacode\0300 \001(\t\022\n\n\002ta\0301 \001(\t\022\022\n\n" +
      "regionCode\0302 \001(\t\022\016\n\006region\0303 \001(\t\022\022\n\nurba" +
      "nRural\0304 \001(\t\022\032\n\022retirementLocation\0305 \001(\t" +
      "\022\r\n\005parID\0306 \001(\t\022\014\n\004mb18\0307 \001(\t\022\016\n\006ta2009\030" +
      "8 \001(\t\022\024\n\014areaUnitCode\0309 \001(\t\022\030\n\020helixPers" +
      "onaCode\030: \001(\t\022\034\n\024landscapePersonaCode\030; " +
      "\001(\t\022\023\n\013addressType\030< \001(\t\022\032\n\022postalAddres" +
      "sLine1\030= \001(\t\022\032\n\022postalAddressLine2\030> \001(\t" +
      "\022\032\n\022postalAddressLine3\030? \001(\t\022\022\n\npostalTo" +
      "wn\030@ \001(\t\022\026\n\016postalPostcode\030A \001(\t\022\021\n\tarfS" +
      "ource\030B \001(\t\022\013\n\003sa1\030C \001(\t\022\013\n\003sa2\030D \001(\t\022\016\n" +
      "\006cnarid\030E \001(\t\022\n\n\002cd\030F \001(\t\022\n\n\002mb\030G \001(\t\022\r\n" +
      "\005malid\030H \001(\t\022\014\n\004elid\030I \001(\t\022\023\n\013countryCod" +
      "e\030J \001(\t\022\017\n\007country\030K \001(\t\022\025\n\rliNZAddressI" +
      "d\030L \001(\t\"\333\006\n\nAUResponse\0228\n\014OutputFields\030\001" +
      " \001(\0132\".AUResponse.AUResponseOutputFields" +
      "\022\025\n\rcorrelationId\030\002 \001(\t\032\373\005\n\026AUResponseOu" +
      "tputFields\022\r\n\005state\030\001 \001(\t\022\020\n\010postCode\030\002 " +
      "\001(\t\022\020\n\010locality\030\003 \001(\t\022\022\n\nstreetName\030\004 \001(" +
      "\t\022\022\n\nstreetType\030\005 \001(\t\022\024\n\014streetSuffix\030\006 " +
      "\001(\t\022\022\n\npostalType\030\007 \001(\t\022\021\n\taddressId\030\010 \001" +
      "(\t\022\020\n\010houseNo1\030\t \001(\t\022\024\n\014houseSuffix1\030\n \001" +
      "(\t\022\020\n\010houseNo2\030\013 \001(\t\022\024\n\014houseSuffix2\030\014 \001" +
      "(\t\022\020\n\010flatType\030\r \001(\t\022\016\n\006flatNo\030\016 \001(\t\022\021\n\t" +
      "levelType\030\017 \001(\t\022\017\n\007levelNo\030\020 \001(\t\022\025\n\rbuil" +
      "dingName1\030\021 \001(\t\022\025\n\rbuildingName2\030\022 \001(\t\022\r" +
      "\n\005lotNo\030\023 \001(\t\022\020\n\010postalNo\030\024 \001(\t\022\024\n\014posta" +
      "lPrefix\030\025 \001(\t\022\024\n\014postalSuffix\030\026 \001(\t\022\014\n\004f" +
      "lag\030\027 \001(\t\022\022\n\nflagString\030\030 \001(\t\022\023\n\013preAddr" +
      "ess1\030\031 \001(\t\022\023\n\013preAddress2\030\032 \001(\t\022\020\n\010addre" +
      "ss1\030\033 \001(\t\022\020\n\010address2\030\034 \001(\t\022\020\n\010address3\030" +
      "\035 \001(\t\022\023\n\013postAddress\030\036 \001(\t\022\023\n\013amendedFla" +
      "g\030\037 \001(\t\022\020\n\010gifFlags\030  \001(\t\022\020\n\010latitude\030! " +
      "\001(\t\022\021\n\tlongitude\030\" \001(\t\022\023\n\013reliability\030# " +
      "\001(\t\022\n\n\002cd\030$ \001(\t\022\n\n\002mb\030% \001(\t\022\013\n\003sa1\030& \001(\t" +
      "\022\r\n\005malid\030\' \001(\t\022\014\n\004elid\030( \001(\t\"}\n\nNZRespo" +
      "nse\022+\n\010response\030\001 \001(\0132\027.NZResponseOutput" +
      "FieldsH\000\022!\n\005error\030\002 \001(\0132\020.NZResponseErro" +
      "rH\000\022\025\n\rcorrelationId\030\003 \001(\tB\010\n\006status\"\320\n\n" +
      "\026NZResponseOutputFields\022\017\n\007nzMALID\030\001 \001(\t" +
      "\022\014\n\004city\030\002 \001(\t\022\020\n\010postcode\030\003 \001(\t\022\016\n\006subu" +
      "rb\030\004 \001(\t\022\022\n\nstreetName\030\005 \001(\t\022\022\n\nstreetTy" +
      "pe\030\006 \001(\t\022\024\n\014streetSuffix\030\007 \001(\t\022\022\n\npostal" +
      "Type\030\010 \001(\t\022\021\n\taddressId\030\t \001(\t\022\020\n\010houseNo" +
      "1\030\n \001(\t\022\024\n\014houseSuffix1\030\013 \001(\t\022\020\n\010houseNo" +
      "2\030\014 \001(\t\022\024\n\014houseSuffix2\030\r \001(\t\022\020\n\010flatTyp" +
      "e\030\016 \001(\t\022\016\n\006flatNo\030\017 \001(\t\022\021\n\tlevelType\030\020 \001" +
      "(\t\022\017\n\007levelNo\030\021 \001(\t\022\025\n\rbuildingName1\030\022 \001" +
      "(\t\022\025\n\rbuildingName2\030\023 \001(\t\022\r\n\005lotNo\030\024 \001(\t" +
      "\022\020\n\010postalNo\030\025 \001(\t\022\024\n\014postalPrefix\030\026 \001(\t" +
      "\022\024\n\014postalSuffix\030\027 \001(\t\022\014\n\004flag\030\030 \001(\t\022\022\n\n" +
      "flagString\030\031 \001(\t\022\023\n\013preAddress1\030\032 \001(\t\022\023\n" +
      "\013preAddress2\030\033 \001(\t\022\020\n\010address1\030\034 \001(\t\022\020\n\010" +
      "address2\030\035 \001(\t\022\020\n\010address3\030\036 \001(\t\022\023\n\013post" +
      "Address\030\037 \001(\t\022\023\n\013amendedFlag\030  \001(\t\022\020\n\010rd" +
      "Number\030! \001(\t\022\021\n\tvalidFlag\030\" \001(\t\022\032\n\022valid" +
      "FlagCorrected\030# \001(\t\022\020\n\010gifFlags\030$ \001(\t\022\020\n" +
      "\010latitude\030% \001(\t\022\021\n\tlongitude\030& \001(\t\022\023\n\013re" +
      "liability\030\' \001(\t\022\014\n\004dpid\030( \001(\t\022\027\n\017mailDel" +
      "iverable\030) \001(\t\022\023\n\013oldPostcode\030* \001(\t\022\r\n\005s" +
      "adid\030+ \001(\t\022\014\n\004mb06\030, \001(\t\022\014\n\004mb13\030- \001(\t\022\020" +
      "\n\010areaUnit\030. \001(\t\022\020\n\010wardDesc\030/ \001(\t\022\016\n\006ta" +
      "code\0300 \001(\t\022\n\n\002ta\0301 \001(\t\022\022\n\nregionCode\0302 \001" +
      "(\t\022\016\n\006region\0303 \001(\t\022\022\n\nurbanRural\0304 \001(\t\022\032" +
      "\n\022retirementLocation\0305 \001(\t\022\r\n\005parID\0306 \001(" +
      "\t\022\014\n\004mb18\0307 \001(\t\022\016\n\006ta2009\0308 \001(\t\022\024\n\014areaU" +
      "nitCode\0309 \001(\t\022\030\n\020helixPersonaCode\030: \001(\t\022" +
      "\034\n\024landscapePersonaCode\030; \001(\t\022\023\n\013address" +
      "Type\030< \001(\t\022\032\n\022postalAddressLine1\030= \001(\t\022\032" +
      "\n\022postalAddressLine2\030> \001(\t\022\032\n\022postalAddr" +
      "essLine3\030? \001(\t\022\022\n\npostalTown\030@ \001(\t\022\026\n\016po" +
      "stalPostcode\030A \001(\t\022\021\n\tarfSource\030B \001(\t\022\013\n" +
      "\003sa1\030C \001(\t\022\013\n\003sa2\030D \001(\t\022\016\n\006cnarid\030E \001(\t\"" +
      "b\n\017NZResponseError\022\021\n\ttimestamp\030\001 \001(\t\022\016\n" +
      "\006status\030\002 \001(\t\022\r\n\005error\030\003 \001(\t\022\017\n\007message\030" +
      "\004 \001(\t\022\014\n\004path\030\005 \001(\t2<\n\025AUAddressStandard" +
      "izer\022#\n\ngetAddress\022\010.Request\032\013.AURespons" +
      "e2<\n\025NZAddressStandardizer\022#\n\ngetAddress" +
      "\022\010.Request\032\013.NZResponse2Y\n\036TransTasmanAd" +
      "dressStandardizer\0227\n\025getTransTasmanAddre" +
      "ss\022\010.Request\032\024.TransTasmanResponseB(\n$co" +
      "m.equifax.fabric.dataprep.geocoderP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "Address", "CorrelationId", });
    internal_static_TransTasmanResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TransTasmanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransTasmanResponse_descriptor,
        new java.lang.String[] { "OutputFields", "CorrelationId", });
    internal_static_TransTasmanResponse_TransTasmanResponseOutputFields_descriptor =
      internal_static_TransTasmanResponse_descriptor.getNestedTypes().get(0);
    internal_static_TransTasmanResponse_TransTasmanResponseOutputFields_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransTasmanResponse_TransTasmanResponseOutputFields_descriptor,
        new java.lang.String[] { "NzMALID", "City", "Postcode", "Suburb", "StreetName", "StreetType", "StreetSuffix", "PostalType", "AddressId", "HouseNo1", "HouseSuffix1", "HouseNo2", "HouseSuffix2", "FlatType", "FlatNo", "LevelType", "LevelNo", "BuildingName1", "BuildingName2", "LotNo", "PostalNo", "PostalPrefix", "PostalSuffix", "Flag", "FlagString", "PreAddress1", "PreAddress2", "Address1", "Address2", "Address3", "PostAddress", "AmendedFlag", "RdNumber", "ValidFlag", "ValidFlagCorrected", "GifFlags", "Latitude", "Longitude", "Reliability", "Dpid", "MailDeliverable", "OldPostcode", "Sadid", "Mb06", "Mb13", "AreaUnit", "WardDesc", "Tacode", "Ta", "RegionCode", "Region", "UrbanRural", "RetirementLocation", "ParID", "Mb18", "Ta2009", "AreaUnitCode", "HelixPersonaCode", "LandscapePersonaCode", "AddressType", "PostalAddressLine1", "PostalAddressLine2", "PostalAddressLine3", "PostalTown", "PostalPostcode", "ArfSource", "Sa1", "Sa2", "Cnarid", "Cd", "Mb", "Malid", "Elid", "CountryCode", "Country", "LiNZAddressId", });
    internal_static_AUResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AUResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AUResponse_descriptor,
        new java.lang.String[] { "OutputFields", "CorrelationId", });
    internal_static_AUResponse_AUResponseOutputFields_descriptor =
      internal_static_AUResponse_descriptor.getNestedTypes().get(0);
    internal_static_AUResponse_AUResponseOutputFields_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AUResponse_AUResponseOutputFields_descriptor,
        new java.lang.String[] { "State", "PostCode", "Locality", "StreetName", "StreetType", "StreetSuffix", "PostalType", "AddressId", "HouseNo1", "HouseSuffix1", "HouseNo2", "HouseSuffix2", "FlatType", "FlatNo", "LevelType", "LevelNo", "BuildingName1", "BuildingName2", "LotNo", "PostalNo", "PostalPrefix", "PostalSuffix", "Flag", "FlagString", "PreAddress1", "PreAddress2", "Address1", "Address2", "Address3", "PostAddress", "AmendedFlag", "GifFlags", "Latitude", "Longitude", "Reliability", "Cd", "Mb", "Sa1", "Malid", "Elid", });
    internal_static_NZResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_NZResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NZResponse_descriptor,
        new java.lang.String[] { "Response", "Error", "CorrelationId", "Status", });
    internal_static_NZResponseOutputFields_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_NZResponseOutputFields_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NZResponseOutputFields_descriptor,
        new java.lang.String[] { "NzMALID", "City", "Postcode", "Suburb", "StreetName", "StreetType", "StreetSuffix", "PostalType", "AddressId", "HouseNo1", "HouseSuffix1", "HouseNo2", "HouseSuffix2", "FlatType", "FlatNo", "LevelType", "LevelNo", "BuildingName1", "BuildingName2", "LotNo", "PostalNo", "PostalPrefix", "PostalSuffix", "Flag", "FlagString", "PreAddress1", "PreAddress2", "Address1", "Address2", "Address3", "PostAddress", "AmendedFlag", "RdNumber", "ValidFlag", "ValidFlagCorrected", "GifFlags", "Latitude", "Longitude", "Reliability", "Dpid", "MailDeliverable", "OldPostcode", "Sadid", "Mb06", "Mb13", "AreaUnit", "WardDesc", "Tacode", "Ta", "RegionCode", "Region", "UrbanRural", "RetirementLocation", "ParID", "Mb18", "Ta2009", "AreaUnitCode", "HelixPersonaCode", "LandscapePersonaCode", "AddressType", "PostalAddressLine1", "PostalAddressLine2", "PostalAddressLine3", "PostalTown", "PostalPostcode", "ArfSource", "Sa1", "Sa2", "Cnarid", });
    internal_static_NZResponseError_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_NZResponseError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NZResponseError_descriptor,
        new java.lang.String[] { "Timestamp", "Status", "Error", "Message", "Path", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
