// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddressStandardizer.proto

package com.equifax.fabric.dataprep.geocoder;

public interface NZResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NZResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.NZResponseOutputFields response = 1;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.NZResponseOutputFields response = 1;</code>
   * @return The response.
   */
  com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields getResponse();
  /**
   * <code>.NZResponseOutputFields response = 1;</code>
   */
  com.equifax.fabric.dataprep.geocoder.NZResponseOutputFieldsOrBuilder getResponseOrBuilder();

  /**
   * <code>.NZResponseError error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.NZResponseError error = 2;</code>
   * @return The error.
   */
  com.equifax.fabric.dataprep.geocoder.NZResponseError getError();
  /**
   * <code>.NZResponseError error = 2;</code>
   */
  com.equifax.fabric.dataprep.geocoder.NZResponseErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>string correlationId = 3;</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <code>string correlationId = 3;</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  public com.equifax.fabric.dataprep.geocoder.NZResponse.StatusCase getStatusCase();
}
