// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddressStandardizer.proto

package com.equifax.fabric.dataprep.geocoder;

public interface NZResponseOutputFieldsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NZResponseOutputFields)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nzMALID = 1;</code>
   * @return The nzMALID.
   */
  java.lang.String getNzMALID();
  /**
   * <code>string nzMALID = 1;</code>
   * @return The bytes for nzMALID.
   */
  com.google.protobuf.ByteString
      getNzMALIDBytes();

  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string postcode = 3;</code>
   * @return The postcode.
   */
  java.lang.String getPostcode();
  /**
   * <code>string postcode = 3;</code>
   * @return The bytes for postcode.
   */
  com.google.protobuf.ByteString
      getPostcodeBytes();

  /**
   * <code>string suburb = 4;</code>
   * @return The suburb.
   */
  java.lang.String getSuburb();
  /**
   * <code>string suburb = 4;</code>
   * @return The bytes for suburb.
   */
  com.google.protobuf.ByteString
      getSuburbBytes();

  /**
   * <code>string streetName = 5;</code>
   * @return The streetName.
   */
  java.lang.String getStreetName();
  /**
   * <code>string streetName = 5;</code>
   * @return The bytes for streetName.
   */
  com.google.protobuf.ByteString
      getStreetNameBytes();

  /**
   * <code>string streetType = 6;</code>
   * @return The streetType.
   */
  java.lang.String getStreetType();
  /**
   * <code>string streetType = 6;</code>
   * @return The bytes for streetType.
   */
  com.google.protobuf.ByteString
      getStreetTypeBytes();

  /**
   * <code>string streetSuffix = 7;</code>
   * @return The streetSuffix.
   */
  java.lang.String getStreetSuffix();
  /**
   * <code>string streetSuffix = 7;</code>
   * @return The bytes for streetSuffix.
   */
  com.google.protobuf.ByteString
      getStreetSuffixBytes();

  /**
   * <code>string postalType = 8;</code>
   * @return The postalType.
   */
  java.lang.String getPostalType();
  /**
   * <code>string postalType = 8;</code>
   * @return The bytes for postalType.
   */
  com.google.protobuf.ByteString
      getPostalTypeBytes();

  /**
   * <code>string addressId = 9;</code>
   * @return The addressId.
   */
  java.lang.String getAddressId();
  /**
   * <code>string addressId = 9;</code>
   * @return The bytes for addressId.
   */
  com.google.protobuf.ByteString
      getAddressIdBytes();

  /**
   * <code>string houseNo1 = 10;</code>
   * @return The houseNo1.
   */
  java.lang.String getHouseNo1();
  /**
   * <code>string houseNo1 = 10;</code>
   * @return The bytes for houseNo1.
   */
  com.google.protobuf.ByteString
      getHouseNo1Bytes();

  /**
   * <code>string houseSuffix1 = 11;</code>
   * @return The houseSuffix1.
   */
  java.lang.String getHouseSuffix1();
  /**
   * <code>string houseSuffix1 = 11;</code>
   * @return The bytes for houseSuffix1.
   */
  com.google.protobuf.ByteString
      getHouseSuffix1Bytes();

  /**
   * <code>string houseNo2 = 12;</code>
   * @return The houseNo2.
   */
  java.lang.String getHouseNo2();
  /**
   * <code>string houseNo2 = 12;</code>
   * @return The bytes for houseNo2.
   */
  com.google.protobuf.ByteString
      getHouseNo2Bytes();

  /**
   * <code>string houseSuffix2 = 13;</code>
   * @return The houseSuffix2.
   */
  java.lang.String getHouseSuffix2();
  /**
   * <code>string houseSuffix2 = 13;</code>
   * @return The bytes for houseSuffix2.
   */
  com.google.protobuf.ByteString
      getHouseSuffix2Bytes();

  /**
   * <code>string flatType = 14;</code>
   * @return The flatType.
   */
  java.lang.String getFlatType();
  /**
   * <code>string flatType = 14;</code>
   * @return The bytes for flatType.
   */
  com.google.protobuf.ByteString
      getFlatTypeBytes();

  /**
   * <code>string flatNo = 15;</code>
   * @return The flatNo.
   */
  java.lang.String getFlatNo();
  /**
   * <code>string flatNo = 15;</code>
   * @return The bytes for flatNo.
   */
  com.google.protobuf.ByteString
      getFlatNoBytes();

  /**
   * <code>string levelType = 16;</code>
   * @return The levelType.
   */
  java.lang.String getLevelType();
  /**
   * <code>string levelType = 16;</code>
   * @return The bytes for levelType.
   */
  com.google.protobuf.ByteString
      getLevelTypeBytes();

  /**
   * <code>string levelNo = 17;</code>
   * @return The levelNo.
   */
  java.lang.String getLevelNo();
  /**
   * <code>string levelNo = 17;</code>
   * @return The bytes for levelNo.
   */
  com.google.protobuf.ByteString
      getLevelNoBytes();

  /**
   * <code>string buildingName1 = 18;</code>
   * @return The buildingName1.
   */
  java.lang.String getBuildingName1();
  /**
   * <code>string buildingName1 = 18;</code>
   * @return The bytes for buildingName1.
   */
  com.google.protobuf.ByteString
      getBuildingName1Bytes();

  /**
   * <code>string buildingName2 = 19;</code>
   * @return The buildingName2.
   */
  java.lang.String getBuildingName2();
  /**
   * <code>string buildingName2 = 19;</code>
   * @return The bytes for buildingName2.
   */
  com.google.protobuf.ByteString
      getBuildingName2Bytes();

  /**
   * <code>string lotNo = 20;</code>
   * @return The lotNo.
   */
  java.lang.String getLotNo();
  /**
   * <code>string lotNo = 20;</code>
   * @return The bytes for lotNo.
   */
  com.google.protobuf.ByteString
      getLotNoBytes();

  /**
   * <code>string postalNo = 21;</code>
   * @return The postalNo.
   */
  java.lang.String getPostalNo();
  /**
   * <code>string postalNo = 21;</code>
   * @return The bytes for postalNo.
   */
  com.google.protobuf.ByteString
      getPostalNoBytes();

  /**
   * <code>string postalPrefix = 22;</code>
   * @return The postalPrefix.
   */
  java.lang.String getPostalPrefix();
  /**
   * <code>string postalPrefix = 22;</code>
   * @return The bytes for postalPrefix.
   */
  com.google.protobuf.ByteString
      getPostalPrefixBytes();

  /**
   * <code>string postalSuffix = 23;</code>
   * @return The postalSuffix.
   */
  java.lang.String getPostalSuffix();
  /**
   * <code>string postalSuffix = 23;</code>
   * @return The bytes for postalSuffix.
   */
  com.google.protobuf.ByteString
      getPostalSuffixBytes();

  /**
   * <code>string flag = 24;</code>
   * @return The flag.
   */
  java.lang.String getFlag();
  /**
   * <code>string flag = 24;</code>
   * @return The bytes for flag.
   */
  com.google.protobuf.ByteString
      getFlagBytes();

  /**
   * <code>string flagString = 25;</code>
   * @return The flagString.
   */
  java.lang.String getFlagString();
  /**
   * <code>string flagString = 25;</code>
   * @return The bytes for flagString.
   */
  com.google.protobuf.ByteString
      getFlagStringBytes();

  /**
   * <code>string preAddress1 = 26;</code>
   * @return The preAddress1.
   */
  java.lang.String getPreAddress1();
  /**
   * <code>string preAddress1 = 26;</code>
   * @return The bytes for preAddress1.
   */
  com.google.protobuf.ByteString
      getPreAddress1Bytes();

  /**
   * <code>string preAddress2 = 27;</code>
   * @return The preAddress2.
   */
  java.lang.String getPreAddress2();
  /**
   * <code>string preAddress2 = 27;</code>
   * @return The bytes for preAddress2.
   */
  com.google.protobuf.ByteString
      getPreAddress2Bytes();

  /**
   * <code>string address1 = 28;</code>
   * @return The address1.
   */
  java.lang.String getAddress1();
  /**
   * <code>string address1 = 28;</code>
   * @return The bytes for address1.
   */
  com.google.protobuf.ByteString
      getAddress1Bytes();

  /**
   * <code>string address2 = 29;</code>
   * @return The address2.
   */
  java.lang.String getAddress2();
  /**
   * <code>string address2 = 29;</code>
   * @return The bytes for address2.
   */
  com.google.protobuf.ByteString
      getAddress2Bytes();

  /**
   * <code>string address3 = 30;</code>
   * @return The address3.
   */
  java.lang.String getAddress3();
  /**
   * <code>string address3 = 30;</code>
   * @return The bytes for address3.
   */
  com.google.protobuf.ByteString
      getAddress3Bytes();

  /**
   * <code>string postAddress = 31;</code>
   * @return The postAddress.
   */
  java.lang.String getPostAddress();
  /**
   * <code>string postAddress = 31;</code>
   * @return The bytes for postAddress.
   */
  com.google.protobuf.ByteString
      getPostAddressBytes();

  /**
   * <code>string amendedFlag = 32;</code>
   * @return The amendedFlag.
   */
  java.lang.String getAmendedFlag();
  /**
   * <code>string amendedFlag = 32;</code>
   * @return The bytes for amendedFlag.
   */
  com.google.protobuf.ByteString
      getAmendedFlagBytes();

  /**
   * <code>string rdNumber = 33;</code>
   * @return The rdNumber.
   */
  java.lang.String getRdNumber();
  /**
   * <code>string rdNumber = 33;</code>
   * @return The bytes for rdNumber.
   */
  com.google.protobuf.ByteString
      getRdNumberBytes();

  /**
   * <code>string validFlag = 34;</code>
   * @return The validFlag.
   */
  java.lang.String getValidFlag();
  /**
   * <code>string validFlag = 34;</code>
   * @return The bytes for validFlag.
   */
  com.google.protobuf.ByteString
      getValidFlagBytes();

  /**
   * <code>string validFlagCorrected = 35;</code>
   * @return The validFlagCorrected.
   */
  java.lang.String getValidFlagCorrected();
  /**
   * <code>string validFlagCorrected = 35;</code>
   * @return The bytes for validFlagCorrected.
   */
  com.google.protobuf.ByteString
      getValidFlagCorrectedBytes();

  /**
   * <code>string gifFlags = 36;</code>
   * @return The gifFlags.
   */
  java.lang.String getGifFlags();
  /**
   * <code>string gifFlags = 36;</code>
   * @return The bytes for gifFlags.
   */
  com.google.protobuf.ByteString
      getGifFlagsBytes();

  /**
   * <code>string latitude = 37;</code>
   * @return The latitude.
   */
  java.lang.String getLatitude();
  /**
   * <code>string latitude = 37;</code>
   * @return The bytes for latitude.
   */
  com.google.protobuf.ByteString
      getLatitudeBytes();

  /**
   * <code>string longitude = 38;</code>
   * @return The longitude.
   */
  java.lang.String getLongitude();
  /**
   * <code>string longitude = 38;</code>
   * @return The bytes for longitude.
   */
  com.google.protobuf.ByteString
      getLongitudeBytes();

  /**
   * <code>string reliability = 39;</code>
   * @return The reliability.
   */
  java.lang.String getReliability();
  /**
   * <code>string reliability = 39;</code>
   * @return The bytes for reliability.
   */
  com.google.protobuf.ByteString
      getReliabilityBytes();

  /**
   * <code>string dpid = 40;</code>
   * @return The dpid.
   */
  java.lang.String getDpid();
  /**
   * <code>string dpid = 40;</code>
   * @return The bytes for dpid.
   */
  com.google.protobuf.ByteString
      getDpidBytes();

  /**
   * <code>string mailDeliverable = 41;</code>
   * @return The mailDeliverable.
   */
  java.lang.String getMailDeliverable();
  /**
   * <code>string mailDeliverable = 41;</code>
   * @return The bytes for mailDeliverable.
   */
  com.google.protobuf.ByteString
      getMailDeliverableBytes();

  /**
   * <code>string oldPostcode = 42;</code>
   * @return The oldPostcode.
   */
  java.lang.String getOldPostcode();
  /**
   * <code>string oldPostcode = 42;</code>
   * @return The bytes for oldPostcode.
   */
  com.google.protobuf.ByteString
      getOldPostcodeBytes();

  /**
   * <code>string sadid = 43;</code>
   * @return The sadid.
   */
  java.lang.String getSadid();
  /**
   * <code>string sadid = 43;</code>
   * @return The bytes for sadid.
   */
  com.google.protobuf.ByteString
      getSadidBytes();

  /**
   * <code>string mb06 = 44;</code>
   * @return The mb06.
   */
  java.lang.String getMb06();
  /**
   * <code>string mb06 = 44;</code>
   * @return The bytes for mb06.
   */
  com.google.protobuf.ByteString
      getMb06Bytes();

  /**
   * <code>string mb13 = 45;</code>
   * @return The mb13.
   */
  java.lang.String getMb13();
  /**
   * <code>string mb13 = 45;</code>
   * @return The bytes for mb13.
   */
  com.google.protobuf.ByteString
      getMb13Bytes();

  /**
   * <code>string areaUnit = 46;</code>
   * @return The areaUnit.
   */
  java.lang.String getAreaUnit();
  /**
   * <code>string areaUnit = 46;</code>
   * @return The bytes for areaUnit.
   */
  com.google.protobuf.ByteString
      getAreaUnitBytes();

  /**
   * <code>string wardDesc = 47;</code>
   * @return The wardDesc.
   */
  java.lang.String getWardDesc();
  /**
   * <code>string wardDesc = 47;</code>
   * @return The bytes for wardDesc.
   */
  com.google.protobuf.ByteString
      getWardDescBytes();

  /**
   * <code>string tacode = 48;</code>
   * @return The tacode.
   */
  java.lang.String getTacode();
  /**
   * <code>string tacode = 48;</code>
   * @return The bytes for tacode.
   */
  com.google.protobuf.ByteString
      getTacodeBytes();

  /**
   * <code>string ta = 49;</code>
   * @return The ta.
   */
  java.lang.String getTa();
  /**
   * <code>string ta = 49;</code>
   * @return The bytes for ta.
   */
  com.google.protobuf.ByteString
      getTaBytes();

  /**
   * <code>string regionCode = 50;</code>
   * @return The regionCode.
   */
  java.lang.String getRegionCode();
  /**
   * <code>string regionCode = 50;</code>
   * @return The bytes for regionCode.
   */
  com.google.protobuf.ByteString
      getRegionCodeBytes();

  /**
   * <code>string region = 51;</code>
   * @return The region.
   */
  java.lang.String getRegion();
  /**
   * <code>string region = 51;</code>
   * @return The bytes for region.
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <code>string urbanRural = 52;</code>
   * @return The urbanRural.
   */
  java.lang.String getUrbanRural();
  /**
   * <code>string urbanRural = 52;</code>
   * @return The bytes for urbanRural.
   */
  com.google.protobuf.ByteString
      getUrbanRuralBytes();

  /**
   * <code>string retirementLocation = 53;</code>
   * @return The retirementLocation.
   */
  java.lang.String getRetirementLocation();
  /**
   * <code>string retirementLocation = 53;</code>
   * @return The bytes for retirementLocation.
   */
  com.google.protobuf.ByteString
      getRetirementLocationBytes();

  /**
   * <code>string parID = 54;</code>
   * @return The parID.
   */
  java.lang.String getParID();
  /**
   * <code>string parID = 54;</code>
   * @return The bytes for parID.
   */
  com.google.protobuf.ByteString
      getParIDBytes();

  /**
   * <code>string mb18 = 55;</code>
   * @return The mb18.
   */
  java.lang.String getMb18();
  /**
   * <code>string mb18 = 55;</code>
   * @return The bytes for mb18.
   */
  com.google.protobuf.ByteString
      getMb18Bytes();

  /**
   * <code>string ta2009 = 56;</code>
   * @return The ta2009.
   */
  java.lang.String getTa2009();
  /**
   * <code>string ta2009 = 56;</code>
   * @return The bytes for ta2009.
   */
  com.google.protobuf.ByteString
      getTa2009Bytes();

  /**
   * <code>string areaUnitCode = 57;</code>
   * @return The areaUnitCode.
   */
  java.lang.String getAreaUnitCode();
  /**
   * <code>string areaUnitCode = 57;</code>
   * @return The bytes for areaUnitCode.
   */
  com.google.protobuf.ByteString
      getAreaUnitCodeBytes();

  /**
   * <code>string helixPersonaCode = 58;</code>
   * @return The helixPersonaCode.
   */
  java.lang.String getHelixPersonaCode();
  /**
   * <code>string helixPersonaCode = 58;</code>
   * @return The bytes for helixPersonaCode.
   */
  com.google.protobuf.ByteString
      getHelixPersonaCodeBytes();

  /**
   * <code>string landscapePersonaCode = 59;</code>
   * @return The landscapePersonaCode.
   */
  java.lang.String getLandscapePersonaCode();
  /**
   * <code>string landscapePersonaCode = 59;</code>
   * @return The bytes for landscapePersonaCode.
   */
  com.google.protobuf.ByteString
      getLandscapePersonaCodeBytes();

  /**
   * <code>string addressType = 60;</code>
   * @return The addressType.
   */
  java.lang.String getAddressType();
  /**
   * <code>string addressType = 60;</code>
   * @return The bytes for addressType.
   */
  com.google.protobuf.ByteString
      getAddressTypeBytes();

  /**
   * <code>string postalAddressLine1 = 61;</code>
   * @return The postalAddressLine1.
   */
  java.lang.String getPostalAddressLine1();
  /**
   * <code>string postalAddressLine1 = 61;</code>
   * @return The bytes for postalAddressLine1.
   */
  com.google.protobuf.ByteString
      getPostalAddressLine1Bytes();

  /**
   * <code>string postalAddressLine2 = 62;</code>
   * @return The postalAddressLine2.
   */
  java.lang.String getPostalAddressLine2();
  /**
   * <code>string postalAddressLine2 = 62;</code>
   * @return The bytes for postalAddressLine2.
   */
  com.google.protobuf.ByteString
      getPostalAddressLine2Bytes();

  /**
   * <code>string postalAddressLine3 = 63;</code>
   * @return The postalAddressLine3.
   */
  java.lang.String getPostalAddressLine3();
  /**
   * <code>string postalAddressLine3 = 63;</code>
   * @return The bytes for postalAddressLine3.
   */
  com.google.protobuf.ByteString
      getPostalAddressLine3Bytes();

  /**
   * <code>string postalTown = 64;</code>
   * @return The postalTown.
   */
  java.lang.String getPostalTown();
  /**
   * <code>string postalTown = 64;</code>
   * @return The bytes for postalTown.
   */
  com.google.protobuf.ByteString
      getPostalTownBytes();

  /**
   * <code>string postalPostcode = 65;</code>
   * @return The postalPostcode.
   */
  java.lang.String getPostalPostcode();
  /**
   * <code>string postalPostcode = 65;</code>
   * @return The bytes for postalPostcode.
   */
  com.google.protobuf.ByteString
      getPostalPostcodeBytes();

  /**
   * <code>string arfSource = 66;</code>
   * @return The arfSource.
   */
  java.lang.String getArfSource();
  /**
   * <code>string arfSource = 66;</code>
   * @return The bytes for arfSource.
   */
  com.google.protobuf.ByteString
      getArfSourceBytes();

  /**
   * <code>string sa1 = 67;</code>
   * @return The sa1.
   */
  java.lang.String getSa1();
  /**
   * <code>string sa1 = 67;</code>
   * @return The bytes for sa1.
   */
  com.google.protobuf.ByteString
      getSa1Bytes();

  /**
   * <code>string sa2 = 68;</code>
   * @return The sa2.
   */
  java.lang.String getSa2();
  /**
   * <code>string sa2 = 68;</code>
   * @return The bytes for sa2.
   */
  com.google.protobuf.ByteString
      getSa2Bytes();

  /**
   * <code>string cnarid = 69;</code>
   * @return The cnarid.
   */
  java.lang.String getCnarid();
  /**
   * <code>string cnarid = 69;</code>
   * @return The bytes for cnarid.
   */
  com.google.protobuf.ByteString
      getCnaridBytes();
}
