// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddressStandardizer.proto

package com.equifax.fabric.dataprep.geocoder;

/**
 * <pre>
 * NZResponse represents the output of the NZ geocoder, which can take on
 * one of two known schemas: a successful response or an error response.
 * In either case, the response is returned to the client. 
 * </pre>
 *
 * Protobuf type {@code NZResponse}
 */
public  final class NZResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NZResponse)
    NZResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NZResponse.newBuilder() to construct.
  private NZResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NZResponse() {
    correlationId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NZResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NZResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.Builder subBuilder = null;
            if (statusCase_ == 1) {
              subBuilder = ((com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields) status_).toBuilder();
            }
            status_ =
                input.readMessage(com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields) status_);
              status_ = subBuilder.buildPartial();
            }
            statusCase_ = 1;
            break;
          }
          case 18: {
            com.equifax.fabric.dataprep.geocoder.NZResponseError.Builder subBuilder = null;
            if (statusCase_ == 2) {
              subBuilder = ((com.equifax.fabric.dataprep.geocoder.NZResponseError) status_).toBuilder();
            }
            status_ =
                input.readMessage(com.equifax.fabric.dataprep.geocoder.NZResponseError.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.equifax.fabric.dataprep.geocoder.NZResponseError) status_);
              status_ = subBuilder.buildPartial();
            }
            statusCase_ = 2;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            correlationId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.equifax.fabric.dataprep.geocoder.AddressStandardizer.internal_static_NZResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.equifax.fabric.dataprep.geocoder.AddressStandardizer.internal_static_NZResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.equifax.fabric.dataprep.geocoder.NZResponse.class, com.equifax.fabric.dataprep.geocoder.NZResponse.Builder.class);
  }

  private int statusCase_ = 0;
  private java.lang.Object status_;
  public enum StatusCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    RESPONSE(1),
    ERROR(2),
    STATUS_NOT_SET(0);
    private final int value;
    private StatusCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StatusCase valueOf(int value) {
      return forNumber(value);
    }

    public static StatusCase forNumber(int value) {
      switch (value) {
        case 1: return RESPONSE;
        case 2: return ERROR;
        case 0: return STATUS_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public StatusCase
  getStatusCase() {
    return StatusCase.forNumber(
        statusCase_);
  }

  public static final int RESPONSE_FIELD_NUMBER = 1;
  /**
   * <code>.NZResponseOutputFields response = 1;</code>
   * @return Whether the response field is set.
   */
  public boolean hasResponse() {
    return statusCase_ == 1;
  }
  /**
   * <code>.NZResponseOutputFields response = 1;</code>
   * @return The response.
   */
  public com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields getResponse() {
    if (statusCase_ == 1) {
       return (com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields) status_;
    }
    return com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.getDefaultInstance();
  }
  /**
   * <code>.NZResponseOutputFields response = 1;</code>
   */
  public com.equifax.fabric.dataprep.geocoder.NZResponseOutputFieldsOrBuilder getResponseOrBuilder() {
    if (statusCase_ == 1) {
       return (com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields) status_;
    }
    return com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.getDefaultInstance();
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  /**
   * <code>.NZResponseError error = 2;</code>
   * @return Whether the error field is set.
   */
  public boolean hasError() {
    return statusCase_ == 2;
  }
  /**
   * <code>.NZResponseError error = 2;</code>
   * @return The error.
   */
  public com.equifax.fabric.dataprep.geocoder.NZResponseError getError() {
    if (statusCase_ == 2) {
       return (com.equifax.fabric.dataprep.geocoder.NZResponseError) status_;
    }
    return com.equifax.fabric.dataprep.geocoder.NZResponseError.getDefaultInstance();
  }
  /**
   * <code>.NZResponseError error = 2;</code>
   */
  public com.equifax.fabric.dataprep.geocoder.NZResponseErrorOrBuilder getErrorOrBuilder() {
    if (statusCase_ == 2) {
       return (com.equifax.fabric.dataprep.geocoder.NZResponseError) status_;
    }
    return com.equifax.fabric.dataprep.geocoder.NZResponseError.getDefaultInstance();
  }

  public static final int CORRELATIONID_FIELD_NUMBER = 3;
  private volatile java.lang.Object correlationId_;
  /**
   * <code>string correlationId = 3;</code>
   * @return The correlationId.
   */
  public java.lang.String getCorrelationId() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      correlationId_ = s;
      return s;
    }
  }
  /**
   * <code>string correlationId = 3;</code>
   * @return The bytes for correlationId.
   */
  public com.google.protobuf.ByteString
      getCorrelationIdBytes() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      correlationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (statusCase_ == 1) {
      output.writeMessage(1, (com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields) status_);
    }
    if (statusCase_ == 2) {
      output.writeMessage(2, (com.equifax.fabric.dataprep.geocoder.NZResponseError) status_);
    }
    if (!getCorrelationIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, correlationId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (statusCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields) status_);
    }
    if (statusCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.equifax.fabric.dataprep.geocoder.NZResponseError) status_);
    }
    if (!getCorrelationIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, correlationId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.equifax.fabric.dataprep.geocoder.NZResponse)) {
      return super.equals(obj);
    }
    com.equifax.fabric.dataprep.geocoder.NZResponse other = (com.equifax.fabric.dataprep.geocoder.NZResponse) obj;

    if (!getCorrelationId()
        .equals(other.getCorrelationId())) return false;
    if (!getStatusCase().equals(other.getStatusCase())) return false;
    switch (statusCase_) {
      case 1:
        if (!getResponse()
            .equals(other.getResponse())) return false;
        break;
      case 2:
        if (!getError()
            .equals(other.getError())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CORRELATIONID_FIELD_NUMBER;
    hash = (53 * hash) + getCorrelationId().hashCode();
    switch (statusCase_) {
      case 1:
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
        break;
      case 2:
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.equifax.fabric.dataprep.geocoder.NZResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.equifax.fabric.dataprep.geocoder.NZResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.equifax.fabric.dataprep.geocoder.NZResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.equifax.fabric.dataprep.geocoder.NZResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.equifax.fabric.dataprep.geocoder.NZResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.equifax.fabric.dataprep.geocoder.NZResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.equifax.fabric.dataprep.geocoder.NZResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.equifax.fabric.dataprep.geocoder.NZResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.equifax.fabric.dataprep.geocoder.NZResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.equifax.fabric.dataprep.geocoder.NZResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.equifax.fabric.dataprep.geocoder.NZResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.equifax.fabric.dataprep.geocoder.NZResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.equifax.fabric.dataprep.geocoder.NZResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * NZResponse represents the output of the NZ geocoder, which can take on
   * one of two known schemas: a successful response or an error response.
   * In either case, the response is returned to the client. 
   * </pre>
   *
   * Protobuf type {@code NZResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NZResponse)
      com.equifax.fabric.dataprep.geocoder.NZResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.equifax.fabric.dataprep.geocoder.AddressStandardizer.internal_static_NZResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.equifax.fabric.dataprep.geocoder.AddressStandardizer.internal_static_NZResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.equifax.fabric.dataprep.geocoder.NZResponse.class, com.equifax.fabric.dataprep.geocoder.NZResponse.Builder.class);
    }

    // Construct using com.equifax.fabric.dataprep.geocoder.NZResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      correlationId_ = "";

      statusCase_ = 0;
      status_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.equifax.fabric.dataprep.geocoder.AddressStandardizer.internal_static_NZResponse_descriptor;
    }

    @java.lang.Override
    public com.equifax.fabric.dataprep.geocoder.NZResponse getDefaultInstanceForType() {
      return com.equifax.fabric.dataprep.geocoder.NZResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.equifax.fabric.dataprep.geocoder.NZResponse build() {
      com.equifax.fabric.dataprep.geocoder.NZResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.equifax.fabric.dataprep.geocoder.NZResponse buildPartial() {
      com.equifax.fabric.dataprep.geocoder.NZResponse result = new com.equifax.fabric.dataprep.geocoder.NZResponse(this);
      if (statusCase_ == 1) {
        if (responseBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = responseBuilder_.build();
        }
      }
      if (statusCase_ == 2) {
        if (errorBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = errorBuilder_.build();
        }
      }
      result.correlationId_ = correlationId_;
      result.statusCase_ = statusCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.equifax.fabric.dataprep.geocoder.NZResponse) {
        return mergeFrom((com.equifax.fabric.dataprep.geocoder.NZResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.equifax.fabric.dataprep.geocoder.NZResponse other) {
      if (other == com.equifax.fabric.dataprep.geocoder.NZResponse.getDefaultInstance()) return this;
      if (!other.getCorrelationId().isEmpty()) {
        correlationId_ = other.correlationId_;
        onChanged();
      }
      switch (other.getStatusCase()) {
        case RESPONSE: {
          mergeResponse(other.getResponse());
          break;
        }
        case ERROR: {
          mergeError(other.getError());
          break;
        }
        case STATUS_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.equifax.fabric.dataprep.geocoder.NZResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.equifax.fabric.dataprep.geocoder.NZResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int statusCase_ = 0;
    private java.lang.Object status_;
    public StatusCase
        getStatusCase() {
      return StatusCase.forNumber(
          statusCase_);
    }

    public Builder clearStatus() {
      statusCase_ = 0;
      status_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields, com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.Builder, com.equifax.fabric.dataprep.geocoder.NZResponseOutputFieldsOrBuilder> responseBuilder_;
    /**
     * <code>.NZResponseOutputFields response = 1;</code>
     * @return Whether the response field is set.
     */
    public boolean hasResponse() {
      return statusCase_ == 1;
    }
    /**
     * <code>.NZResponseOutputFields response = 1;</code>
     * @return The response.
     */
    public com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields getResponse() {
      if (responseBuilder_ == null) {
        if (statusCase_ == 1) {
          return (com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields) status_;
        }
        return com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.getDefaultInstance();
      } else {
        if (statusCase_ == 1) {
          return responseBuilder_.getMessage();
        }
        return com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.getDefaultInstance();
      }
    }
    /**
     * <code>.NZResponseOutputFields response = 1;</code>
     */
    public Builder setResponse(com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        responseBuilder_.setMessage(value);
      }
      statusCase_ = 1;
      return this;
    }
    /**
     * <code>.NZResponseOutputFields response = 1;</code>
     */
    public Builder setResponse(
        com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.Builder builderForValue) {
      if (responseBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        responseBuilder_.setMessage(builderForValue.build());
      }
      statusCase_ = 1;
      return this;
    }
    /**
     * <code>.NZResponseOutputFields response = 1;</code>
     */
    public Builder mergeResponse(com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields value) {
      if (responseBuilder_ == null) {
        if (statusCase_ == 1 &&
            status_ != com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.getDefaultInstance()) {
          status_ = com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.newBuilder((com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields) status_)
              .mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        if (statusCase_ == 1) {
          responseBuilder_.mergeFrom(value);
        }
        responseBuilder_.setMessage(value);
      }
      statusCase_ = 1;
      return this;
    }
    /**
     * <code>.NZResponseOutputFields response = 1;</code>
     */
    public Builder clearResponse() {
      if (responseBuilder_ == null) {
        if (statusCase_ == 1) {
          statusCase_ = 0;
          status_ = null;
          onChanged();
        }
      } else {
        if (statusCase_ == 1) {
          statusCase_ = 0;
          status_ = null;
        }
        responseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.NZResponseOutputFields response = 1;</code>
     */
    public com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.Builder getResponseBuilder() {
      return getResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.NZResponseOutputFields response = 1;</code>
     */
    public com.equifax.fabric.dataprep.geocoder.NZResponseOutputFieldsOrBuilder getResponseOrBuilder() {
      if ((statusCase_ == 1) && (responseBuilder_ != null)) {
        return responseBuilder_.getMessageOrBuilder();
      } else {
        if (statusCase_ == 1) {
          return (com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields) status_;
        }
        return com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.getDefaultInstance();
      }
    }
    /**
     * <code>.NZResponseOutputFields response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields, com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.Builder, com.equifax.fabric.dataprep.geocoder.NZResponseOutputFieldsOrBuilder> 
        getResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        if (!(statusCase_ == 1)) {
          status_ = com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.getDefaultInstance();
        }
        responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields, com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields.Builder, com.equifax.fabric.dataprep.geocoder.NZResponseOutputFieldsOrBuilder>(
                (com.equifax.fabric.dataprep.geocoder.NZResponseOutputFields) status_,
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      statusCase_ = 1;
      onChanged();;
      return responseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.equifax.fabric.dataprep.geocoder.NZResponseError, com.equifax.fabric.dataprep.geocoder.NZResponseError.Builder, com.equifax.fabric.dataprep.geocoder.NZResponseErrorOrBuilder> errorBuilder_;
    /**
     * <code>.NZResponseError error = 2;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return statusCase_ == 2;
    }
    /**
     * <code>.NZResponseError error = 2;</code>
     * @return The error.
     */
    public com.equifax.fabric.dataprep.geocoder.NZResponseError getError() {
      if (errorBuilder_ == null) {
        if (statusCase_ == 2) {
          return (com.equifax.fabric.dataprep.geocoder.NZResponseError) status_;
        }
        return com.equifax.fabric.dataprep.geocoder.NZResponseError.getDefaultInstance();
      } else {
        if (statusCase_ == 2) {
          return errorBuilder_.getMessage();
        }
        return com.equifax.fabric.dataprep.geocoder.NZResponseError.getDefaultInstance();
      }
    }
    /**
     * <code>.NZResponseError error = 2;</code>
     */
    public Builder setError(com.equifax.fabric.dataprep.geocoder.NZResponseError value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }
      statusCase_ = 2;
      return this;
    }
    /**
     * <code>.NZResponseError error = 2;</code>
     */
    public Builder setError(
        com.equifax.fabric.dataprep.geocoder.NZResponseError.Builder builderForValue) {
      if (errorBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      statusCase_ = 2;
      return this;
    }
    /**
     * <code>.NZResponseError error = 2;</code>
     */
    public Builder mergeError(com.equifax.fabric.dataprep.geocoder.NZResponseError value) {
      if (errorBuilder_ == null) {
        if (statusCase_ == 2 &&
            status_ != com.equifax.fabric.dataprep.geocoder.NZResponseError.getDefaultInstance()) {
          status_ = com.equifax.fabric.dataprep.geocoder.NZResponseError.newBuilder((com.equifax.fabric.dataprep.geocoder.NZResponseError) status_)
              .mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        if (statusCase_ == 2) {
          errorBuilder_.mergeFrom(value);
        }
        errorBuilder_.setMessage(value);
      }
      statusCase_ = 2;
      return this;
    }
    /**
     * <code>.NZResponseError error = 2;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        if (statusCase_ == 2) {
          statusCase_ = 0;
          status_ = null;
          onChanged();
        }
      } else {
        if (statusCase_ == 2) {
          statusCase_ = 0;
          status_ = null;
        }
        errorBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.NZResponseError error = 2;</code>
     */
    public com.equifax.fabric.dataprep.geocoder.NZResponseError.Builder getErrorBuilder() {
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.NZResponseError error = 2;</code>
     */
    public com.equifax.fabric.dataprep.geocoder.NZResponseErrorOrBuilder getErrorOrBuilder() {
      if ((statusCase_ == 2) && (errorBuilder_ != null)) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        if (statusCase_ == 2) {
          return (com.equifax.fabric.dataprep.geocoder.NZResponseError) status_;
        }
        return com.equifax.fabric.dataprep.geocoder.NZResponseError.getDefaultInstance();
      }
    }
    /**
     * <code>.NZResponseError error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.equifax.fabric.dataprep.geocoder.NZResponseError, com.equifax.fabric.dataprep.geocoder.NZResponseError.Builder, com.equifax.fabric.dataprep.geocoder.NZResponseErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        if (!(statusCase_ == 2)) {
          status_ = com.equifax.fabric.dataprep.geocoder.NZResponseError.getDefaultInstance();
        }
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.equifax.fabric.dataprep.geocoder.NZResponseError, com.equifax.fabric.dataprep.geocoder.NZResponseError.Builder, com.equifax.fabric.dataprep.geocoder.NZResponseErrorOrBuilder>(
                (com.equifax.fabric.dataprep.geocoder.NZResponseError) status_,
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      statusCase_ = 2;
      onChanged();;
      return errorBuilder_;
    }

    private java.lang.Object correlationId_ = "";
    /**
     * <code>string correlationId = 3;</code>
     * @return The correlationId.
     */
    public java.lang.String getCorrelationId() {
      java.lang.Object ref = correlationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string correlationId = 3;</code>
     * @return The bytes for correlationId.
     */
    public com.google.protobuf.ByteString
        getCorrelationIdBytes() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string correlationId = 3;</code>
     * @param value The correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      correlationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string correlationId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrelationId() {
      
      correlationId_ = getDefaultInstance().getCorrelationId();
      onChanged();
      return this;
    }
    /**
     * <code>string correlationId = 3;</code>
     * @param value The bytes for correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      correlationId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NZResponse)
  }

  // @@protoc_insertion_point(class_scope:NZResponse)
  private static final com.equifax.fabric.dataprep.geocoder.NZResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.equifax.fabric.dataprep.geocoder.NZResponse();
  }

  public static com.equifax.fabric.dataprep.geocoder.NZResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NZResponse>
      PARSER = new com.google.protobuf.AbstractParser<NZResponse>() {
    @java.lang.Override
    public NZResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NZResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NZResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NZResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.equifax.fabric.dataprep.geocoder.NZResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

