// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddressStandardizer.proto

package com.equifax.fabric.dataprep.geocoder;

public interface NZResponseErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NZResponseError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string timestamp = 1;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 1;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string error = 3;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 3;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>string message = 4;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string path = 5;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 5;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
