// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddressStandardizer.proto

package com.equifax.fabric.dataprep.geocoder;

public interface TransTasmanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransTasmanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TransTasmanResponse.TransTasmanResponseOutputFields OutputFields = 1;</code>
   * @return Whether the outputFields field is set.
   */
  boolean hasOutputFields();
  /**
   * <code>.TransTasmanResponse.TransTasmanResponseOutputFields OutputFields = 1;</code>
   * @return The outputFields.
   */
  com.equifax.fabric.dataprep.geocoder.TransTasmanResponse.TransTasmanResponseOutputFields getOutputFields();
  /**
   * <code>.TransTasmanResponse.TransTasmanResponseOutputFields OutputFields = 1;</code>
   */
  com.equifax.fabric.dataprep.geocoder.TransTasmanResponse.TransTasmanResponseOutputFieldsOrBuilder getOutputFieldsOrBuilder();

  /**
   * <code>string correlationId = 2;</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <code>string correlationId = 2;</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();
}
